### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by BannerBomb** [jaylineko/discohook#3]
If you replace the array in the JSON Data for embeds it crashes
![image](https://user-images.githubusercontent.com/11788894/70287842-5e255d00-179e-11ea-8f9b-1a9c02b3e9af.png)
dont put an array for the embeds value, instead attempt to put an object.
![image](https://user-images.githubusercontent.com/11788894/70287869-76957780-179e-11ea-969e-05d247bd2add.png)

**Comment by BannerBomb** [comment]
Same if you attempt to put an array inside an array for the embeds value like
```js
"embeds": [
    [
        {}
    ]
]
```
![image](https://user-images.githubusercontent.com/11788894/70294009-14de0900-17b0-11ea-95a0-c789e4a49ace.png)

**Comment by jaylineko** [comment]
Both of these errors have been fixed in beef87c39299da028d2a188a732db4c530edbff1.

**Comment by BannerBomb** [comment]
Has the site already been updated to fix the issues? Because making `embeds` value an array still crashes it.
![image](https://user-images.githubusercontent.com/11788894/70371178-eb031000-189d-11ea-89a0-7eb45ec5ddde.png)

First delete the `[` and all characters that come after it up until the first `{` then scroll all the way down and remove the last `]` and attempt to place `}` in it's place.

**Comment by BannerBomb** [comment]
@jaylineko Has the site already been updated to fix the issues? Because making `embeds` value an array still crashes it.
![image](https://user-images.githubusercontent.com/11788894/70371178-eb031000-189d-11ea-89a0-7eb45ec5ddde.png)

First delete the `[` and all characters that come after it up until the first `{` then scroll all the way down and remove the last `]` and attempt to place `}` in it's place.

**Comment by jaylineko** [comment]
It has,

Just to be clear, the following JSON data no longer crashes Discohook:
```
{
  "content": "test message",
  "embeds": {
    "title": "with an embed, but wrong"
  }
}
```
Instead, it reports the error "`$.embeds: Must be array`" to the user in a red box.

Try a hard refresh to be sure, if that doesn't help paste the JSON data after the edits (in the state that makes discohook crash) into a reply.

**Comment by BannerBomb** [comment]
seems fixed now, thanks.
